### ISSUE TITLE
Hidden columns are not searchable

### ISSUE THREAD

**Issue by PetrDlouhy** [morlandi/django-ajax-datatable#20]
I wanted to add filter on hidden column by javascript, but even if I explicitly set the column as:
```python
 {'name': 'is_private', 'visible': False, 'searchable': True},
```
it is not possible to search in it.
I fixed this by overriding the searchable value:
```python
    def filter_queryset(self, params, qs):
        # fix hidden column searchable
        params['column_links'][11].searchable = True
        return super().filter_queryset(params, qs)
```

**Comment by morlandi** [comment]
Searching in a hidden column is certainly something usefull.
I'll fix it on the first occasion.

**Comment by morlandi** [comment]
This is puzzling, since I double-checked it and it seems to work as expected.
Sure, you have to explicitly set `'searchable': True` when the column is hidden, since the default is: True if visible, False otherwise.
But you already did this.
Might be more related to searching in a boolean field?
Could you please check again?
I'm closing the issue now, but feel free to reopen it in case

**Comment by PetrDlouhy** [comment]
@morlandi Yes, I am searching in boolean field. I will investigate this more.

**Comment by PetrDlouhy** [comment]
@morlandi I found what is the problem. There are switched parameters in the `ColumnLink` initialization in `read_parameters`. I will make PR.

**Comment by morlandi** [comment]
How surprising !
I just checked in the original project I started from; the bug is already there and dated 4 feb 2016:

https://github.com/monnierj/django-datatables-server-side/blob/master/django_datatables_server_side/views.py
