### ISSUE TITLE
Reload table with new data

### ISSUE THREAD

**Issue by amirj700** [morlandi/django-ajax-datatable#3]
Hi Morlandi, 
Thanks for your good library, I was able to initialize my table with some extra data in 'initialize_table' function. now I'm looking for a method to reinitialize or reload the table with a bunch of new extra data. is there any way? I tried a few methods with table.ajax.reload() but they produced confusing errors. 

any help is appreciated.

**Comment by morlandi** [comment]
Hello @amirj700,
in the README, you can find this snippet:

```
AjaxDatatableViewUtils.initialize_table(
    ...
    }, {
        // extra_data
        client_id: '{{client.id}}',
        date_from: function() { return date_input_to_isoformat('#date_from'); },
        date_to: function() { return date_input_to_isoformat('#date_to'); }
    }
);
```
As you can see, you're not limited to specify constant values: you can pass JS functions as well.

This gives you more flexibility since you can adjust the return values of these functions based on some context variables. I suggest you check if this is enough to solve your use case.

For reloading tables, see:

- https://github.com/morlandi/django-ajax-datatable#63redraw-table-holding-the-current-paging-position

and check these two helpers (file `ajax_datatable/static/ajax_datatable/js/utils.js`):

- AjaxDatatableViewUtils.redraw_all_tables()
- AjaxDatatableViewUtils.redraw_table(element)
