### ISSUE TITLE
Null/empty searches?

### ISSUE THREAD

**Issue by jpuerto-psc** [morlandi/django-ajax-datatable#31]
Wanted to reach out to see if there were any options for null/empty searches? Doesn't seem possible with text searches, nor with the select searches.

Thank you in advance,

Juan

**Comment by morlandi** [comment]
Hello @jpuerto-psc, thank you for interesting and inspirational question.

In the current implementation, hem .. the short answer is "no".
Column filters are based on input and select widgets, and not much can be easily done apart from simple matching of column values. 
Mhhh ... mumble mumble ....

I do believe your request is just an example of the many occasions where, due to the specific context, a complex or custom filtering is needed.
A possible solution is suggested here:

https://github.com/morlandi/django-ajax-datatable#provide-extra-data-to-narrow-down-the-initial-queryset

I tested that technique with the use case you suggested, and added a detailed solution (and explanation) to the example project:

https://github.com/morlandi/django-ajax-datatable#18add-a-sidebar-with-custom-filters

You might want to check if, with a few adaptations, that can be applied to your code too.

**Comment by jpuerto-psc** [comment]
Thanks for the advice @morlandi. I can definitely understand the complication with implementing this at the column header level.

I realize that as of now, the searching is entirely text based; however, it may be helpful to include some level of "symbolic" searching in the columns. For example, this particular situation could be resolved if I could do a `!= ''` search in a column. This would also make searching more intuitive for numeric fields. Perhaps something to consider.

If there was a way to make the searching functionality overridable - I could implement this myself; however, I would really prefer not to have to fork this library and modify core functionality to do so.

Best,

Juan

**Comment by morlandi** [comment]
I recently added the capability to search multiple values on a single columns; that is, you can type "a + b" to search "a" OR "b", as explained here: 

https://github.com/morlandi/django-ajax-datatable#112filtering-multiple-values

This might be a good starting point; the relevant code can be found here:

- AjaxDatatableView._filter_queryset()
- filters.build_column_filter()

You can adapt it to your specific needs, or if you think of a way to express this in a generale and reusable manner, we can discuss about the feasibility to include as a new feature
